# docker-compose.production.yml
version: '3'

volumes:
  static:
  backend_static:
  backend_media:
  postgres_data:


# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    image: alexrossom/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
  frontend:
    image: alexrossom/foodgram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/app/result_build/build
  gateway:
    image: alexrossom/foodgram_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - backend_static:/backend_static
      - backend_media:/backend_media
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 8500:80