# docker-compose.production.yml
version: '3'

volumes:
  pg_data:
  static:


# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: alexrossom/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
  frontend:
    image: alexrossom/foodgram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: alexrossom/foodgram_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/static
    ports:
      - 8500:80