# Generated by Django 3.2 on 2023-09-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ingredientinrecipe_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=0, upload_to='app/', verbose_name='Изображение рецепта'),
            preserve_default=False,
        ),
    ]
